task_name: "activation_extraction_ppr10k/negative"

data:
  dataset_name: "ppr10k"
  feedback_dataset_path: "experiments/ppr10k_data_student/ppr10k/InternVL3_5-8B-HF/zero_shot_memorability_prompt"
  testset_scenes_path: "config/test_set_scenes_seed42.json"
  filter_criteria: "less_higher_two_elements"

model: 
  provider: "hf"
  name: "OpenGVLab/InternVL3_5-8B-HF"
  max_new_tokens: 1024
  use_flash_attention_2: true
  batch_size: 4

activation_settings:
  module: "residual"

prompt:
  version: "training_prompt"